-- Durable cleanup for private Storage objects whose authoritative DB row was
-- deleted. Client-side best-effort removal remains fast, while this queue
-- guarantees a server retry path after network/process failures.

create table if not exists public.storage_cleanup_jobs (
  id bigint generated by default as identity primary key,
  bucket_id text not null check (
    bucket_id in (
      'chat-images',
      'memory-album-photos',
      'travel-city-photos',
      'world-country-photos'
    )
  ),
  object_path text not null check (length(trim(object_path)) > 0),
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  available_at timestamptz not null default now(),
  locked_at timestamptz,
  worker_id text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (bucket_id, object_path)
);

create index if not exists storage_cleanup_jobs_claim_idx
  on public.storage_cleanup_jobs(status, available_at, id);

alter table public.storage_cleanup_jobs enable row level security;
revoke all on table public.storage_cleanup_jobs from public, anon, authenticated;

create or replace function public.enqueue_storage_cleanup(
  target_bucket text,
  target_path text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if target_path is null or trim(target_path) = '' then
    return;
  end if;
  if target_bucket not in (
    'chat-images',
    'memory-album-photos',
    'travel-city-photos',
    'world-country-photos'
  ) then
    raise exception 'STORAGE_CLEANUP_BUCKET_NOT_ALLOWED';
  end if;

  insert into public.storage_cleanup_jobs(bucket_id, object_path)
  values (target_bucket, target_path)
  on conflict (bucket_id, object_path) do update
  set status = 'pending',
      available_at = now(),
      locked_at = null,
      worker_id = null,
      last_error = null,
      updated_at = now();
end;
$$;

revoke all on function public.enqueue_storage_cleanup(text, text)
  from public, anon, authenticated;

create or replace function public.queue_deleted_storage_object()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  bucket_name text := tg_argv[0];
  path_column text := tg_argv[1];
  deleted_path text;
begin
  deleted_path := to_jsonb(old) ->> path_column;
  perform public.enqueue_storage_cleanup(bucket_name, deleted_path);
  return old;
end;
$$;

drop trigger if exists messages_queue_deleted_image on public.messages;
create trigger messages_queue_deleted_image
after delete on public.messages
for each row
when (old.image_path is not null)
execute function public.queue_deleted_storage_object('chat-images', 'image_path');

drop trigger if exists memory_photos_queue_deleted_image
  on public.memory_album_photos;
create trigger memory_photos_queue_deleted_image
after delete on public.memory_album_photos
for each row
execute function public.queue_deleted_storage_object(
  'memory-album-photos',
  'storage_path'
);

drop trigger if exists travel_photos_queue_deleted_image
  on public.travel_city_photos;
create trigger travel_photos_queue_deleted_image
after delete on public.travel_city_photos
for each row
execute function public.queue_deleted_storage_object(
  'travel-city-photos',
  'storage_path'
);

drop trigger if exists world_photos_queue_deleted_image
  on public.world_country_photos;
create trigger world_photos_queue_deleted_image
after delete on public.world_country_photos
for each row
execute function public.queue_deleted_storage_object(
  'world-country-photos',
  'storage_path'
);

create or replace function public.claim_storage_cleanup_jobs(
  worker_id text,
  batch_size integer default 50
)
returns table (
  id bigint,
  bucket_id text,
  object_path text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with candidates as (
    select job.id
    from public.storage_cleanup_jobs job
    where (
      job.status = 'pending'
      and job.available_at <= now()
    ) or (
      job.status = 'processing'
      and job.locked_at < now() - interval '10 minutes'
    )
    order by job.available_at, job.id
    for update skip locked
    limit greatest(1, least(coalesce(batch_size, 50), 100))
  ), claimed as (
    update public.storage_cleanup_jobs job
    set status = 'processing',
        locked_at = now(),
        worker_id = claim_storage_cleanup_jobs.worker_id,
        attempts = job.attempts + 1,
        updated_at = now()
    from candidates
    where job.id = candidates.id
    returning job.id, job.bucket_id, job.object_path
  )
  select claimed.id, claimed.bucket_id, claimed.object_path
  from claimed;
end;
$$;

create or replace function public.finish_storage_cleanup_job(
  target_job_id bigint,
  succeeded boolean,
  error_message text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  attempt_count integer;
begin
  if succeeded then
    delete from public.storage_cleanup_jobs where id = target_job_id;
    return;
  end if;

  select attempts into attempt_count
  from public.storage_cleanup_jobs
  where id = target_job_id;

  update public.storage_cleanup_jobs
  set status = case when coalesce(attempt_count, 0) >= 8
      then 'failed' else 'pending' end,
      available_at = now() +
        make_interval(secs => least(3600, (30 * power(2, greatest(0,
          coalesce(attempt_count, 1) - 1)))::integer)),
      locked_at = null,
      worker_id = null,
      last_error = left(coalesce(error_message, 'STORAGE_REMOVE_FAILED'), 1000),
      updated_at = now()
  where id = target_job_id;
end;
$$;

revoke all on function public.claim_storage_cleanup_jobs(text, integer)
  from public, anon, authenticated;
revoke all on function public.finish_storage_cleanup_job(bigint, boolean, text)
  from public, anon, authenticated;
grant execute on function public.claim_storage_cleanup_jobs(text, integer)
  to service_role;
grant execute on function public.finish_storage_cleanup_job(bigint, boolean, text)
  to service_role;

create or replace function public.invoke_storage_cleanup_worker()
returns void
language plpgsql
security definer
set search_path = public, vault, net
as $$
declare
  project_url text;
  service_role_key text;
begin
  select decrypted_secret into project_url
  from vault.decrypted_secrets
  where name = 'project_url'
  limit 1;

  select decrypted_secret into service_role_key
  from vault.decrypted_secrets
  where name = 'service_role_key'
  limit 1;

  if project_url is null or service_role_key is null then
    raise warning 'storage cleanup worker skipped: vault secrets missing';
    return;
  end if;

  perform net.http_post(
    url := rtrim(project_url, '/') || '/functions/v1/process-storage-cleanup',
    headers := jsonb_build_object(
      'content-type', 'application/json',
      'authorization', 'Bearer ' || service_role_key
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 50000
  );
end;
$$;

revoke all on function public.invoke_storage_cleanup_worker()
  from public, anon, authenticated;
grant execute on function public.invoke_storage_cleanup_worker()
  to service_role;

do $$
declare
  existing_job_id bigint;
begin
  select jobid into existing_job_id
  from cron.job
  where jobname = 'dear-storage-cleanup'
  limit 1;
  if existing_job_id is not null then
    perform cron.unschedule(existing_job_id);
  end if;
  perform cron.schedule(
    'dear-storage-cleanup',
    '*/5 * * * *',
    $command$select public.invoke_storage_cleanup_worker();$command$
  );
end $$;
